#!/bin/sh

export EMAIL="user@example.com"
export DLCACHE="$HOME/tmp/dl"

export PERL_VERSION="5.16.3"

export STATICPERL="$HOME/.staticperl-$PERL_VERSION"
export LIBHOME="$STATICPERL/lib/CORE"

# at ~/staticperl configure || kept for Feersum and other modules
# at ~/staticperl install comment this line
export PERL_LDFLAGS="-Wl,--no-gc-sections -Wl,--allow-multiple-definition"

# change on your taste
export PERL_CONFIGURE="-Duse64bitint -Duselargefiles" #-Dusedl

# ask questions in cpan
#export PERL_MM_USE_DEFAULT=0

# DBD::Oracle
#export LD_RUN_PATH="/usr/lib/oracle/11.2/client64/lib"
#export LD_LIBRARY_PATH="/usr/lib/oracle/11.2/client64/lib"
#export ORACLE_HOME="/usr/lib/oracle/11.2/client64"
#export ORACLE_BASE="/usr/lib/oracle"

# dir with patched modules by gh0stwizard
export SPERL_MODS="$HOME/tmp/staticperl-modules/modules"


# postinstall functions

upgradeModules() {
    instsrc $SPERL_MODS/Class-Load-0.22
    instcpan Class::Load::XS
    
    instsrc $SPERL_MODS/Params-Classify-0.013
    instsrc $SPERL_MODS/Params-Validate-1.17

    instcpan Class::Singleton
    instcpan Math::Round
    instcpan DateTime::Locale
    instcpan List::AllUtils
    instcpan DateTime::TimeZone
    instsrc $SPERL_MODS/DateTime-1.18
}

mypostinstall() {
    instcpan Test::LeakTrace
    instcpan Test::Requires
    instcpan Test::Harness
    instcpan Sub::Uplevel
    instcpan Test::Exception
    instcpan Test::Simple
    instcpan Devel::Symdump
    instcpan Pod::Coverage
    instcpan Test::Pod::Coverage
    instcpan Test::Pod
    instcpan Tree::DAG_Node
    instcpan Test::Warn
    instcpan Sub::Install
    instcpan Params::Util
    instcpan Data::OptList
    instcpan Sub::Exporter 
    instcpan Test::Output
    instcpan Try::Tiny
    instcpan Test::Fatal
    instcpan Test::Tester
    instcpan Test::NoWarnings
    instcpan Test::Tester
    instcpan Test::Deep
    instcpan Params::Util
    instcpan List::MoreUtils
    instcpan Module::Runtime
    instcpan Module::Implementation
    instcpan Sub::Exporter
    instcpan Dist::CheckConflicts
    instcpan Package::DeprecationManager
    instcpan Package::Stash

    instcpan Test::SharedFork
    instcpan Test::TCP
    instcpan Test::Warnings

    instcpan Sub::Exporter::Progressive
    instcpan Devel::GlobalDestruction
    instcpan Dist::CheckConflicts
    instcpan Data::Compare

    instcpan MIME::Base64

    instcpan IO::AIO
    instcpan EV
    instcpan Guard
    instcpan AnyEvent
    instcpan Coro
    instcpan JSON::XS
    instcpan JSON 
    instcpan Async::Interrupt
    instcpan EV::Loop::Async

    instcpan IO::FDPass
    instcpan Proc::FastSpawn

# see patch notes
#    instcpan AnyEvent::Fork AnyEvent::Fork::Pool
}


# Modules below will be installed automatically during
# ~/staticperl install stage
#
# Comment out and change as you wish

#postinstall() {
# upgrade common modules
#    upgradeModules

# install XML::LibXML
#    instcpan XML::NamespaceSupport XML::SAX::Base XML::SAX
#    instcpan XML::LibXML

# install dev mods
#    mypostinstall
#}
