---
abstract: 'A date and time object for Perl'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Storable: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  Test::Warnings: '0.005'
  perl: '5.008001'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  DateTime::Locale: '0.41'
  DateTime::TimeZone: '1.74'
  POSIX: '0'
  Params::Validate: '0.76'
  Scalar::Util: '0'
  Try::Tiny: '0'
  XSLoader: '0'
  base: '0'
  constant: '0'
  integer: '0'
  overload: '0'
  perl: '5.008001'
  strict: '0'
  vars: '0'
  warnings: '0'
  warnings::register: '0'
version: '1.18'
