---
abstract: 'Edit configuration files through Augeas C library'
author:
  - 'Raphaël Pinson (raphink at cpan dot org)'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150001'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Augeas
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.008001'
version: '1.000'
