---
abstract: 'Perl bindings for UnQLite'
author:
  - 'tokuhirom tokuhirom@gmail.com'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: UnQLite
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.05'
