---
abstract: 'XS implementation of parts of Class::Load'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Module::Implementation: '0.04'
  Test::Fatal: '0'
  Test::More: '0.88'
  Test::Requires: '0'
  constant: '0'
  lib: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-Load-XS
no_index:
  directory:
    - t
    - xt
    - examples
    - share
provides:
  Class::Load::XS:
    file: lib/Class/Load/XS.pm
    version: '0.08'
requires:
  Class::Load: '0.20'
  XSLoader: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  IRC: irc://irc.perl.org/#moose
  MailingList: http://lists.perl.org/list/moose.html
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Class-Load-XS
  homepage: https://github.com/moose/Class-Load-XS
  repository: https://github.com/moose/Class-Load-XS.git
version: '0.08'
x_Dist_Zilla:
  perl:
    version: '5.019008'
  plugins:
    -
      class: Dist::Zilla::Plugin::SurgicalPodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Contributors
              name: Contributors
              version: '0.007'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: -Transformer
              version: '4.006'
      name: SurgicalPodWeaver
      version: '0.0021'
    -
      class: Dist::Zilla::Plugin::PPPort
      name: PPPort
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::ETHER/Git::NextVersion'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 0
          check_all_prereqs: 0
          modules:
            - Dist::Zilla::PluginBundle::Author::ETHER
          phase: build
          skip: []
      name: '@Author::ETHER/build'
      version: '0.017'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: '1'
          check_all_prereqs: '1'
          modules: []
          phase: release
          skip: []
      name: '@Author::ETHER/release'
      version: '0.017'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ETHER/ExecDir'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ETHER/ShareDir'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FileFinder::ByName
      name: '@Author::ETHER/Examples'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::ETHER/Git::GatherDir'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ETHER/MetaYAML'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::ETHER/MetaJSON'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ETHER/License'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ETHER/Readme'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ETHER/Manifest'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::GenerateFile::ShareDir
      config:
        Dist::Zilla::Plugin::GenerateFile::ShareDir:
          destination_filename: CONTRIBUTING
          dist: Dist-Zilla-PluginBundle-Author-ETHER
          encoding: UTF-8
          source_filename: CONTRIBUTING
      name: '@Author::ETHER/generate CONTRIBUTING'
      version: '0.005'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: xt/author/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
            - '@Author::ETHER/Examples'
      name: '@Author::ETHER/Test::Compile'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
            - '@Author::ETHER/Examples'
      name: '@Author::ETHER/Test::NoTabs'
      version: '0.06'
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::ETHER/EOLTests'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::ETHER/MetaTests'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::ETHER/Test::Version'
      version: '0.002004'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::ETHER/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@Author::ETHER/Test::ChangesHasContent'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@Author::ETHER/Test::UnusedVars'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::ETHER/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::ETHER/PodSyntaxTests'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::ETHER/PodCoverageTests'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@Author::ETHER/Test::PodSpelling'
      version: '2.006002'
    -
      class: Dist::Zilla::Plugin::Test::Pod::No404s
      name: '@Author::ETHER/Test::Pod::No404s'
      version: '1.001'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::ETHER/Test::Kwalitee'
      version: '2.07'
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@Author::ETHER/MojibakeTests'
      version: '0.5'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::ETHER/Test::ReportPrereqs'
      version: '0.013'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::ETHER/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@Author::ETHER/Git::Describe'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::ETHER/PkgVersion'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::ETHER/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::ETHER/NextRelease'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::ETHER/ReadmeAnyFromPod'
      version: '0.133360'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::ETHER/GithubMeta'
      version: '0.42'
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::ETHER/AutoMetaResources'
      version: '1.20'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::ETHER/MetaNoIndex'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder:
            - ':InstallModules'
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: ':InstallModules'
              version: '5.013'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@Author::ETHER/MetaProvides::Package'
      version: '2.000001'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ETHER/MetaConfig'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ETHER/AutoPrereqs'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Prereqs::AuthorDeps
      name: '@Author::ETHER/Prereqs::AuthorDeps'
      version: '0.002'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::ETHER/MinimumPerl'
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::ETHER/installer_requirements'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: recommends
      name: '@Author::ETHER/pluginbundle_version'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Author::ETHER/RunExtraTests'
      version: '0.016'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::ETHER/MakeMaker'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::ETHER/InstallGuide'
      version: '1.200002'
    -
      class: Dist::Zilla::Plugin::CheckSelfDependency
      config:
        Dist::Zilla::Plugin::CheckSelfDependency:
          finder:
            - ':InstallModules'
      name: '@Author::ETHER/CheckSelfDependency'
      version: '0.007'
    -
      class: Dist::Zilla::Plugin::Run::AfterBuild
      name: '@Author::ETHER/Run::AfterBuild'
      version: '0.020'
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::ETHER/initial check'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      name: '@Author::ETHER/Git::CheckFor::MergeConflicts'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::ETHER/Git::CheckFor::CorrectBranch'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: '@Author::ETHER/Git::Remote::Check'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::ETHER/CheckPrereqsIndexed'
      version: '0.010'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ETHER/TestRelease'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::ETHER/after tests'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ETHER/UploadToCPAN'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromRelease
      name: '@Author::ETHER/CopyFilesFromRelease'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::ETHER/Git::Commit'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::ETHER/Git::Tag'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Author::ETHER/GitHub::Update'
      version: '0.36'
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::ETHER/Git::Push'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ETHER/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::ETHER/via_options'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ETHER/ConfirmRelease'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: ContributorsFromGit
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.013'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.013'
x_authority: cpan:SARTAK
x_contributors:
  - 'Jesse Luehrs <doy@tozt.net>'
  - 'Karen Etheridge <ether@cpan.org>'
