---
abstract: 'Text::Markdown::Hoedown is binding library for hoedown.'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  Test::More: '0'
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Markdown-Hoedown
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::ParseXS: '3.22'
  parent: '0'
version: '1.01'
