---
abstract: 'Extremely fast HTML escape'
author:
  - 'Goro Fuji, Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Devel::PPPort: '3.20'
  Test::More: '0.98'
  Test::Requires: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Escape
no_index:
  directory:
    - t
    - inc
requires: {}
version: '1.10'
