---
abstract: 'Validate method/function parameters'
author:
  - 'Dave Rolsky, <autarch@urth.org> and Ilya Martynov <ilya@martynov.org>'
build_requires:
  Devel::Peek: 0
  File::Spec: 0
  File::Temp: 0
  Module::Implementation: 0.04
  Test::Fatal: 0
  Test::More: 0.88
  Tie::Array: 0
  Tie::Hash: 0
  base: 0
  overload: 0
  perl: 5.008001
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Validate
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: 0.79
  Carp: 0
  Exporter: 0
  Module::Implementation: 0
  Scalar::Util: 1.10
  XSLoader: 0
  attributes: 0
  strict: 0
  vars: 0
  warnings: 0
version: 1.13
